name: SoulBuyer
version: '${version}'
main: bm.b0b0b0.soulBuyer.SoulBuyer
api-version: '1.21'
authors: [ b0b0b0 ]
load: POSTWORLD
softdepend: [ Vault, PlayerPoints, Essentials, PlaceholderAPI ]
commands:
  soulbuyer:
    description: SoulBuyer resource seller
    usage: /soulbuyer
  buyer:
    description: Open SoulBuyer menu
    usage: /buyer
  sell:
    description: Open SoulBuyer menu
    usage: /sell
  sb:
    description: Open SoulBuyer menu
    usage: /sb
  rbuyer:
    description: Open SoulBuyer menu
    usage: /rbuyer
  bs:
    description: Open SoulBuyer menu
    usage: /bs
  donbuyer:
    description: Open donate SoulBuyer menu (PlayerPoints)
    usage: /donbuyer
  dbuyer:
    description: Open donate SoulBuyer menu
    usage: /dbuyer
  ppbuyer:
    description: Open donate SoulBuyer menu
    usage: /ppbuyer
  donatesell:
    description: Open donate SoulBuyer menu
    usage: /donatesell
permissions:
  soulbuyer.use:
    description: Open buyer menu
    default: true
  soulbuyer.admin:
    description: Admin commands
    default: op
  soulbuyer.autosell:
    description: Donator autosell on pickup
    default: op
  soulbuyer.donate:
    description: Open donate buyer menu (PlayerPoints)
    default: true
  soulbuyer.multiplier.vip:
    description: VIP income multiplier tier
    default: false
  soulbuyer.multiplier.premium:
    description: Premium income multiplier tier
    default: false
libraries:
  - net.elytrium:serializer:1.1.1
  - com.zaxxer:HikariCP:5.1.0
  - com.mysql:mysql-connector-j:8.4.0
  - org.xerial:sqlite-jdbc:3.46.1.3
  - redis.clients:jedis:5.1.0
